# Numpy

In [29]:
import numpy as np

## Array

### Section-1

Example-1



In [81]:
a = np.array(
    [
        1, 2, 3, 4, 5
    ]
)
print("ndim:", a.ndim)      # number of dimensions
print("shape:", a.shape)    # size of each dimension
print("dtype:", a.dtype)    # data type
print("Max:", np.max(a))    # Max
print("Min:", np.min(a))    # Min
print("Sum:", np.sum(a))    # Sum

ndim: 1
shape: (5,)
dtype: int64
Max: 5
Min: 1
Sum: 15


Example-2

In [94]:
a = np.array(
    [
        [1, 2, 3, 4, 5] ,
        [4, 5, 6, 7, 8]
    ]
)
print("ndim:", a.ndim)
print("shape:", a.shape)
print("dtype:", a.dtype)

ndim: 2
shape: (2, 5)
dtype: int64


Example-3

In [95]:
a = np.array(
    [
        [
            [ 1,  2,  3,  4, 5],
            [ 5,  6,  7,  8, 9],
            [ 9, 10, 11, 12, 13]
        ],
        [
            [13, 14, 15, 16, 17],
            [17, 18, 19, 20, 18],
            [21, 22, 23, 24, 19]
        ]
    ]
)
print("ndim:", a.ndim)
print("shape:", a.shape)
print("dtype:", a.dtype)


ndim: 3
shape: (2, 3, 5)
dtype: int64


### Section-2

Example-1

In [68]:
a = np.arange(1, 15)
b = np.arange(1, 15, 3)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  4  7 10 13]


Example-2

In [75]:
a = np.linspace(1, 15, 10)
print(a)
len(a)

[ 1.          2.55555556  4.11111111  5.66666667  7.22222222  8.77777778
 10.33333333 11.88888889 13.44444444 15.        ]


10

### Section-3

In [96]:
m1 = np.full((4, 5), 1)
m2 = np.full((4, 5), 2)
m3 = np.full((5), 3)
print(m1)
print(m2)
print(m3)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
[3 3 3 3 3]


In [97]:
r = m1*m2
print(r)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [98]:
r = m1 @ m2.T  # Transpose m2
print(r)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [93]:
r = m1.dot(m2.T)  # Transpose m2
print(r)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
