# Numpy

In [256]:
import numpy as np

## Array

In [257]:
a = np.array(
    [
        1, 2, 3, 4, 5
    ]
)
print("array:", a)
print("shape:", a.shape)
print("shape:", np.shape(a))
print("dtype:", a.dtype)    # data type
print("Max:", a.max())      # Max
print("Min:", a.min())      # Min
print("Sum:", a.sum())      # Sum
print("size:", a.size)      # size
print("item-size:", a.itemsize)  # itemsize

array: [1 2 3 4 5]
shape: (5,)
shape: (5,)
dtype: int64
Max: 5
Min: 1
Sum: 15
size: 5
item-size: 8


In [258]:
a = np.array(
    [
        1, 2, 3, 4, 5
    ]
)
print("ndim:", a.ndim)      # number of dimensions
print("shape:", a.shape)    # size of each dimension

ndim: 1
shape: (5,)


In [259]:
a = np.array(
    [
        [1, 2, 3, 4, 5] ,
        [4, 5, 6, 7, 8]
    ]
)
print("ndim:", a.ndim)
print("shape:", a.shape)

ndim: 2
shape: (2, 5)


In [260]:
a = np.array(
    [
        [
            [ 1,  2,  3,  4, 5],
            [ 5,  6,  7,  8, 9],
            [ 9, 10, 11, 12, 13]
        ],
        [
            [13, 14, 15, 16, 17],
            [17, 18, 19, 20, 18],
            [21, 22, 23, 24, 19]
        ]
    ]
)
print("ndim:", a.ndim)
print("shape:", a.shape)


ndim: 3
shape: (2, 3, 5)


## Change

### ReShape

In [261]:
a = np.array(
    [
      [ 1,  2,  3,  4, 5],
      [ 6,  7,  8,  9, 10],
      [ 11, 12, 13, 14, 15]
    ]
)
print("shape:", a.shape)

shape: (3, 5)


In [262]:
b = a.reshape(5,3)
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


## Where

In [263]:
a = np.array(
    [
      [ 1,  2,  3,  4, 5],
      [ 6,  7,  8,  9, 10],
      [ 11, 12, 13, 14, 15]
    ]
)

In [264]:
a>14

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True]])

In [265]:
print(np.sum(a>14))

1


In [266]:
np.where(a>14, 1, 0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1]])

## Fill

### Zeros

In [267]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Ones

In [268]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Full

In [269]:
m1 = np.full((4, 5), 1)
m2 = np.full((4, 5), 2)
m3 = np.full((5), 3)
print(m1)
print(m2)
print(m3)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
[3 3 3 3 3]


### Arange

In [270]:
a = np.arange(1, 15)
b = np.arange(1, 15, 3)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  4  7 10 13]


### Linspace

In [271]:
a = np.linspace(1, 15, 10)
print(a)
len(a)

[ 1.          2.55555556  4.11111111  5.66666667  7.22222222  8.77777778
 10.33333333 11.88888889 13.44444444 15.        ]


10

## Random

### rand

In [272]:
np.random.rand(5)

array([0.31403157, 0.65758997, 0.92662401, 0.81574072, 0.95032824])

In [273]:
np.random.rand(3, 5)

array([[0.133181  , 0.41120716, 0.00277255, 0.62408199, 0.43978641],
       [0.25897163, 0.38928358, 0.79587357, 0.93046879, 0.00229946],
       [0.49937119, 0.42311563, 0.43840421, 0.54384951, 0.33993848]])

### random

In [274]:
np.random.random(5)

array([0.89108172, 0.82799168, 0.58441256, 0.24017589, 0.83838132])

In [275]:
np.random.random((3,5))

array([[0.66942819, 0.25664834, 0.44363572, 0.85247808, 0.64162703],
       [0.7977059 , 0.35654771, 0.70252065, 0.75617513, 0.29005343],
       [0.20880989, 0.28503974, 0.46383034, 0.63404265, 0.05619154]])

### randint

In [276]:
a = np.random.randint(10)
b = np.random.randint(5, 15)
c = np.random.randint(5, 15, 3)
d = np.random.randint(0, 9, 9).reshape((3,3))
print("a:", a)
print("b:", b)
print("c:", c)
print("d:", d)

a: 9
b: 9
c: [11  6  7]
d: [[5 0 8]
 [2 0 4]
 [5 4 3]]


### shuffle

In [277]:
a = np.arange(1,22).reshape((7,3))
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [278]:
np.random.shuffle(a)
print(a)

[[10 11 12]
 [ 4  5  6]
 [ 1  2  3]
 [19 20 21]
 [ 7  8  9]
 [13 14 15]
 [16 17 18]]


### normal

In [282]:
np.random.normal()

1.6788068985939455

In [284]:
np.random.normal(size=5)

array([-1.79122971,  0.79290761, -1.60394048, -1.20730558, -1.98129495])

### uniform

In [285]:
np.random.uniform()

0.5379778578504014

In [287]:
np.random.uniform(size=5)

array([0.11247261, 0.81057467, 0.05388243, 0.25379226, 0.7022459 ])

### choice

In [294]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]

4
[4 2]


In [296]:
print(np.random.choice(a))

2


In [298]:
print(np.random.choice(a, size=2))

[6 8]


In [300]:
print(np.random.choice(a, size=(3, 3)))

[[8 2 3]
 [6 2 1]
 [5 7 1]]


## Amaliat

In [279]:
r = m1*m2
print(r)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [280]:
r = m1 @ m2.T  # Transpose m2
print(r)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [281]:
r = m1.dot(m2.T)  # Transpose m2
print(r)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
